// Bundles tools/orb/entry.js into a TypeScript module holding the script as a
// string, so the setup page can inline it: the page works offline and loads
// nothing from anywhere. Run after upgrading thinking-orbs:
//   node tools/orb/build.mjs
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const pkg = path.join(repo, 'packages', 'core', 'node_modules', 'thinking-orbs');
const version = JSON.parse(readFileSync(path.join(pkg, 'package.json'), 'utf8')).version;
const license = readFileSync(path.join(pkg, 'LICENSE'), 'utf8').trim();

const out = await build({
  entryPoints: [path.join(here, 'entry.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  write: false,
  nodePaths: [path.join(repo, 'packages', 'core', 'node_modules')],
});
const js = out.outputFiles[0].text.trim();

const target = path.join(repo, 'packages', 'core', 'src', 'ui', 'orb.generated.ts');
writeFileSync(
  target,
  [
    '// Generated by tools/orb/build.mjs -- do not edit.',
    `// Contains thinking-orbs ${version}:`,
    ...license.split('\n').map((l) => `// ${l}`.trimEnd()),
    '',
    `export const ORB_SCRIPT = ${JSON.stringify(js)};`,
    '',
  ].join('\n'),
);
console.log(`${path.relative(repo, target)}: ${String(js.length)} bytes`);
