#!/usr/bin/env node
// Builds the Windows client: one executable, one installer.
//
// There is no window shell on Windows (D-061 / D-074): the program itself is
// the client. Double-clicking it starts the setup page in an Edge app window,
// exactly as the Mac client's shell starts it in a WKWebView. So the whole
// "client" here is the single-file executable -- what this script adds is the
// icon and version stamp, and an NSIS installer that puts it somewhere and
// makes a shortcut.
//
// The executable is built here rather than reused, because the icon has to be
// stamped before postject injects the blob: after injection the resource
// section sits where the Authenticode signature was, and a PE editor handed
// that file never finishes (D-074). So this script runs `build-sea.mjs` with
// the stamp hook, then packages whatever came out.
//
// Usage: node scripts/build-windows.mjs   (after `pnpm run build` at the root)

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { decodePng, encodeIco } from './lib/icon.mjs';

const pkg = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(path.join(pkg, 'package.json'), 'utf8'));
// One directory per platform; see build-linux.mjs for why.
const release = path.join(pkg, 'release', 'win-x64');
const work = path.join(release, 'work');
const sea = path.join(pkg, '..', 'cli', 'sea', 'lingspark.exe');
const setup = path.join(release, `lingspark-${version}-win-x64-setup.exe`);

const run = (cmd, args) => execFileSync(cmd, args, { stdio: 'inherit', shell: cmd.endsWith('.cmd') });

if (process.platform !== 'win32') {
  console.error('Windows 客户端只能在 Windows 上构建。');
  process.exit(1);
}

rmSync(release, { recursive: true, force: true });
mkdirSync(work, { recursive: true });

// The icon Explorer shows on the file, in the task bar and in the Start menu:
// the same picture the Mac app uses, packed as an .ico (D-074). Written before
// the stamp step runs, which is where the installer picks it up too.
const iconPath = path.join(work, 'icon.ico');
writeFileSync(iconPath, encodeIco([16, 24, 32, 48, 64, 128, 256], decodePng(readFileSync(path.join(pkg, 'build', 'icon.png')))));

// The executable, stamped and injected in one go.
run(process.execPath, [
  path.join(pkg, '..', 'cli', 'scripts', 'build-sea.mjs'),
  '--stamp',
  path.join(pkg, 'scripts', 'stamp-win.mjs'),
]);

if (!existsSync(sea)) {
  console.error(`构建 SEA 之后仍然找不到 ${sea}。`);
  process.exit(1);
}

// The installer script. Written out rather than kept as a checked-in file so
// the version and the paths into work/ cannot drift from this script.
//
// The BOM is not decoration: without it makensis reads this file as the
// machine's ANSI code page, so on a Chinese Windows the "卸载" below was
// written out as mojibake (the Start-menu shortcut really was named
// "鍗歌浇.lnk"). With the BOM it is decoded as UTF-8 wherever the installer is
// built, which is also where the installer itself is going to run.
const nsi = path.join(work, 'installer.nsi');
// Spelled out rather than pasted in: an invisible character in source is one
// more thing to trip over in a diff, and ESLint rightly rejects it.
const BOM = String.fromCharCode(0xfeff);
writeFileSync(
  nsi,
  `${BOM}; LingSpark Windows installer, generated by scripts/build-windows.mjs.
Unicode true
RequestExecutionLevel user      ; per-user: no administrator prompt, and the
                                   ; hooks only ever touch the user's own files
InstallDir "$LOCALAPPDATA\\Programs\\LingSpark"
InstallDirRegKey HKCU "Software\\LingSpark" "InstallDir"
Name "LingSpark"
OutFile "${setup.replace(/\\/g, '\\\\')}"
SetCompressor /SOLID lzma

!include "MUI2.nsh"

!define MUI_ABORTWARNING
!define MUI_ICON "${iconPath.replace(/\\/g, '\\\\')}"
!define MUI_UNICON "${iconPath.replace(/\\/g, '\\\\')}"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "SimpChinese"

Section "LingSpark" SecMain
  SectionIn RO
  ; The program is the client: no resources, no helper process. Double-clicking
  ; it opens the setup page in a window of its own (D-074).
  SetOutPath "$INSTDIR"
  File "${sea.replace(/\\/g, '\\\\')}"

  CreateDirectory "$SMPROGRAMS\\LingSpark"
  ; The icon comes from the installed program, not from the .ico this build
  ; wrote: work/ is deleted a few lines after makensis runs, and a shortcut
  ; that points into it keeps the path it was given instead of copying the
  ; picture -- so every shortcut on the machine ends up with a blank icon.
  ; Windows takes the icon out of the exe, which carries it for good (D-074).
  CreateShortcut "$SMPROGRAMS\\LingSpark\\LingSpark.lnk" "$INSTDIR\\lingspark.exe" "" "$INSTDIR\\lingspark.exe"
  CreateShortcut "$SMPROGRAMS\\LingSpark\\卸载.lnk" "$INSTDIR\\uninstall.exe" "" "$INSTDIR\\lingspark.exe"
  CreateShortcut "$DESKTOP\\LingSpark.lnk" "$INSTDIR\\lingspark.exe" "" "$INSTDIR\\lingspark.exe"

  ; The hooks run an absolute path to a copy this program makes on first use,
  ; so nothing else in the system needs to know where it was installed.
  WriteRegStr HKCU "Software\\LingSpark" "InstallDir" "$INSTDIR"

  WriteUninstaller "$INSTDIR\\uninstall.exe"
SectionEnd

Section "Uninstall"
  Delete "$DESKTOP\\LingSpark.lnk"
  Delete "$SMPROGRAMS\\LingSpark\\LingSpark.lnk"
  Delete "$SMPROGRAMS\\LingSpark\\卸载.lnk"
  RMDir "$SMPROGRAMS\\LingSpark"
  ; The data directory (config, cache, session state) is the user's, not the
  ; program's, so it stays. Remove it by hand from %APPDATA%\\lingspark.
  Delete "$INSTDIR\\lingspark.exe"
  Delete "$INSTDIR\\uninstall.exe"
  RMDir "$INSTDIR"
  DeleteRegKey HKCU "Software\\LingSpark"
SectionEnd
`,
);

// NSIS is the one build input this script cannot produce itself, and it is
// installed two incompatible ways. `choco install nsis` shims makensis onto
// PATH; the stock installer from nsis.sourceforge.io drops it into Program
// Files and never touches PATH at all. Looking only at MAKENSIS and the bare
// name therefore worked on CI and failed on an ordinary Windows box that had
// NSIS sitting right there. So ask the standard directories too -- harmless
// when they do not exist -- and report where we looked when it still fails.
const makensisCandidates = () =>
  [
    process.env['MAKENSIS'],
    'makensis',
    ...[process.env['ProgramFiles(x86)'], process.env.ProgramFiles]
      .filter((dir) => dir)
      .map((dir) => path.join(dir, 'NSIS', 'makensis.exe')),
    path.join(process.env['LOCALAPPDATA'] ?? '', 'Programs', 'NSIS', 'makensis.exe'),
  ].filter((cmd) => cmd);

const findMakensis = () => {
  const tried = [];
  for (const cmd of makensisCandidates()) {
    try {
      // /VERSION is the cheapest thing makensis does, and running it is the
      // only way to tell a working makensis from a stale path.
      execFileSync(cmd, ['/VERSION'], { stdio: 'ignore' });
      return { cmd, tried };
    } catch {
      tried.push(cmd);
    }
  }
  return { cmd: null, tried };
};

const { cmd: makensis, tried } = findMakensis();
if (!makensis) {
  console.error('找不到 NSIS（makensis）。装上之后重试：');
  console.error('  Windows：winget install NSIS.NSIS  或  choco install nsis');
  console.error('  已经装好了的话，设置 MAKENSIS 指向 makensis.exe 的完整路径。');
  console.error(`  找过：${tried.join('  ')}`);
  process.exit(1);
}
run(makensis, [`/V3`, nsi]);

rmSync(work, { recursive: true, force: true });

const mb = (p) => (statSync(p).size / 1024 / 1024).toFixed(0);
console.log(`LingSpark 安装程序 -> ${path.relative(process.cwd(), setup)} (${mb(setup)} MB)`);
console.log(`命令行版即该安装包里的 lingspark.exe（${mb(sea)} MB），也可从 Releases 单独下载。`);
