#!/usr/bin/env node
// The Windows installer script, as text (D-074 / D-080).
//
// Written out by the build rather than kept as a checked-in file so the version
// and the paths into work/ cannot drift from the script that packages it -- and
// in a module of its own so the layout can be tested without running makensis
// (installer.test.mjs).
//
// Two programs go in, and they are not interchangeable (D-080):
//
//   $INSTDIR\lingspark.exe            the command-line program: hooks, setup,
//                                    the checks. This is what the task manager
//                                    shows while a check runs.
//   $INSTDIR\client\LingSpark.exe     the client: a window, and nothing else.
//                                    The subdirectory is not tidiness -- on a
//                                    Windows disk "LingSpark.exe" and
//                                    "lingspark.exe" are one name, so side by
//                                    side the client would find itself.

import path from 'node:path';

/** Spelled out rather than pasted in: an invisible character in source is one more thing to trip over in a diff. */
const BOM = String.fromCharCode(0xfeff);

/**
 * @param {object} paths
 * @param {string} paths.setup   the .exe to write, absolute
 * @param {string} paths.sea     the command-line program, absolute
 * @param {string} paths.client  the client's directory (work/client), absolute
 * @param {string} paths.icon    the .ico, absolute
 * @returns {string} the .nsi source, BOM included
 */
export function windowsNsi({ setup, sea, client, icon }) {
  const nsi = (p) => p.replace(/\\/g, '\\\\');
  const clientFiles = [
    'LingSpark.exe',
    'Microsoft.Web.WebView2.Core.dll',
    'Microsoft.Web.WebView2.WinForms.dll',
    'WebView2Loader.dll',
  ];
  return `${BOM}; LingSpark Windows installer, generated by scripts/build-windows.mjs.
Unicode true
RequestExecutionLevel user      ; per-user: no administrator prompt, and the
                                   ; hooks only ever touch the user's own files
InstallDir "$LOCALAPPDATA\\Programs\\LingSpark"
InstallDirRegKey HKCU "Software\\LingSpark" "InstallDir"
Name "LingSpark"
OutFile "${nsi(setup)}"
SetCompressor /SOLID lzma

!include "MUI2.nsh"

!define MUI_ABORTWARNING
!define MUI_ICON "${nsi(icon)}"
!define MUI_UNICON "${nsi(icon)}"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "SimpChinese"

Section "LingSpark" SecMain
  SectionIn RO
  ; The command-line program, at the top of the directory: it is the one the
  ; hooks run and the one a terminal user types.
  SetOutPath "$INSTDIR"
  File "${nsi(sea)}"

  ; The client, in a directory of its own (see the head of this file).
  SetOutPath "$INSTDIR\\client"
${clientFiles.map((name) => `  File "${nsi(path.join(client, name))}"`).join('\n')}

  CreateDirectory "$SMPROGRAMS\\LingSpark"
  ; The icon comes from the installed program, not from the .ico this build
  ; wrote: work/ is deleted a few lines after makensis runs, and a shortcut
  ; that points into it keeps the path it was given instead of copying the
  ; picture -- so every shortcut on the machine ends up with a blank icon.
  ; Windows takes the icon out of the exe, which carries it for good (D-074).
  CreateShortcut "$SMPROGRAMS\\LingSpark\\LingSpark.lnk" "$INSTDIR\\client\\LingSpark.exe" "" "$INSTDIR\\client\\LingSpark.exe"
  CreateShortcut "$SMPROGRAMS\\LingSpark\\卸载.lnk" "$INSTDIR\\uninstall.exe" "" "$INSTDIR\\client\\LingSpark.exe"
  CreateShortcut "$DESKTOP\\LingSpark.lnk" "$INSTDIR\\client\\LingSpark.exe" "" "$INSTDIR\\client\\LingSpark.exe"

  ; The hooks run an absolute path to a copy this program makes on first use,
  ; so nothing else in the system needs to know where it was installed.
  WriteRegStr HKCU "Software\\LingSpark" "InstallDir" "$INSTDIR"

  WriteUninstaller "$INSTDIR\\uninstall.exe"
SectionEnd

Section "Uninstall"
  Delete "$DESKTOP\\LingSpark.lnk"
  Delete "$SMPROGRAMS\\LingSpark\\LingSpark.lnk"
  Delete "$SMPROGRAMS\\LingSpark\\卸载.lnk"
  RMDir "$SMPROGRAMS\\LingSpark"
  ; The data directory (config, cache, session state) is the user's, not the
  ; program's, so it stays. Remove it by hand from %APPDATA%\\lingspark.
  Delete "$INSTDIR\\lingspark.exe"
${clientFiles.map((name) => `  Delete "$INSTDIR\\client\\${name}"`).join('\n')}
  RMDir "$INSTDIR\\client"
  Delete "$INSTDIR\\uninstall.exe"
  RMDir "$INSTDIR"
  DeleteRegKey HKCU "Software\\LingSpark"
SectionEnd
`;
}
