import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { AgentProfile } from '../agents.js';
import { HOOK_TIMEOUT_POST_S, HOOK_TIMEOUT_STOP_S } from '../constants.js';
import { InstallError, applyChange, planChange } from './install.js';
import { msg } from '../messages.js';
import { ourCommandsInText, withPluginInstalled, withPluginRemoved } from './merge.js';
import type { HookCommand } from './merge.js';

/**
 * Bridge agents (pi, opencode) have no shell-hook config; they load a JS/TS
 * extension instead. lingspark ships a tiny bridge file that translates the
 * agent's extension events into the same `lingspark hook` command the other
 * agents run, feeding it the same Claude-format JSON on stdin. The runtime
 * (parseHookInput/runHook) is untouched; only installation and detection know
 * about bridges (DECISIONS D-102).
 */

const hookCommand = (agent: string, cmd: HookCommand, event: string): string =>
  `${cmd.posix} hook --agent ${agent} --event ${event}`;

/**
 * The hook command as [exe, ...args]. currentHookCommand always double-quotes
 * every path and refuses paths it cannot quote, so splitting on quoted runs is
 * exact. spawnSync needs this shape anyway: with `shell: true` on Windows the
 * payload would be piped to cmd.exe, which swallows stdin instead of forwarding
 * it to the child -- the hook then sees an empty payload and passes everything
 * (found in the live pi/opencode verification, D-102).
 */
function splitCommand(posix: string): string[] {
  const parts = [...posix.matchAll(/"([^"]*)"/gu)].map((m) => m[1] ?? '');
  if (parts.length === 0 || parts.some((p) => p.length === 0)) {
    throw new InstallError(msg.install.bridgeWriteFailed(posix, 'unquoted hook command'));
  }
  return parts;
}

/**
 * The runtime source shared by both bridge templates. `esm` emits import
 * statements instead of require: opencode loads plugins as ES modules, where a
 * top-level require is undefined and kills the whole plugin (its loader does
 * not reparse ambiguous files the way Node does -- found live, D-102). pi's
 * jiti loader accepts require in its TS extensions, so it keeps the CJS form.
 */
function bridgeRuntime(agent: string, cmd: HookCommand, esm: boolean): string {
  const post = JSON.stringify(hookCommand(agent, cmd, 'post-tool-use'));
  const stop = JSON.stringify(hookCommand(agent, cmd, 'stop'));
  const postParts = JSON.stringify([...splitCommand(cmd.posix), 'hook', '--agent', agent, '--event', 'post-tool-use']);
  const stopParts = JSON.stringify([...splitCommand(cmd.posix), 'hook', '--agent', agent, '--event', 'stop']);
  const imports = esm
    ? [
        "import { spawnSync } from 'node:child_process';",
        "import { readFileSync, rmSync, writeFileSync } from 'node:fs';",
      ]
    : [
        "const { spawnSync } = require('node:child_process');",
        "const { readFileSync, rmSync, writeFileSync } = require('node:fs');",
      ];
  return [
    '// LingSpark hook bridge. Generated by `lingspark install` (D-102); edits are overwritten.',
    '// It translates the host agent\'s extension events into lingspark hook commands,',
    '// feeding them the same JSON the other agents send on stdin.',
    ...imports,
    `// What it runs, for humans and for lingspark's installed-detection:`,
    `const POST_CMD = ${post};`,
    `const STOP_CMD = ${stop};`,
    `const POST = ${postParts};`,
    `const STOP = ${stopParts};`,
    `const POST_TIMEOUT = ${String(HOOK_TIMEOUT_POST_S)} * 1000;`,
    `const STOP_TIMEOUT = ${String(HOOK_TIMEOUT_STOP_S)} * 1000;`,
    '// lingspark drives this agent as a judging child sometimes: its hooks must',
    '// stand down then, or judging would recurse into more judging.',
    "const JUDGING = process.env.LINGSPARK_JUDGE_CHILD === '1';",
    '// Runs one hook; returns the feedback text when it blocked (exit 2), else null.',
    '// No shell: cmd.exe would swallow the stdin payload on its way to the child.',
    'function run(parts, timeout, payload) {',
    '  if (JUDGING) return null;',
    '  try {',
    '    const r = spawnSync(parts[0], parts.slice(1), {',
    '      input: JSON.stringify(payload),',
    '      encoding: "utf8",',
    '      timeout,',
    '      maxBuffer: 16 * 1024 * 1024,',
    '      windowsHide: true,',
    '    });',
    "    if (r.error || r.status !== 2) return null;",
    '    return (r.stderr ?? "").trim() || "LingSpark 拦下了这次写入";',
    '  } catch {',
    '    return null;',
    '  }',
    '}',
    '// pi and opencode fire their hooks BEFORE the tool runs, so a fresh write is',
    '// not on disk yet and a disk read would check nothing. Mirror the content the',
    '// tool is about to write to a sibling temp file, check that, then delete it.',
    '// (Found in live verification, D-102.)',
    'function mirror(targetPath, content) {',
    '  if (typeof targetPath !== "string" || targetPath.length === 0) return null;',
    '  const tmp = `${targetPath}.lingspark-mirror-${process.pid}.md`;',
    '  try {',
    '    writeFileSync(tmp, content, "utf8");',
    '    return tmp;',
    '  } catch {',
    '    return null;',
    '  }',
    '}',
  ].join('\n');
}

function piExtension(agent: AgentProfile, cmd: HookCommand): string {
  return `${bridgeRuntime(agent.id, cmd, false)}
// write takes {path, content}; edit takes {path, edits:[{oldText, newText}]};
// bash/powershell take {command} (checked on disk when the file exists).
const WRITE_TOOLS = new Set(["write", "edit", "bash", "powershell"]);

export default function (pi: any): void {
  pi.on("tool_call", async (event: any, ctx: any) => {
    if (!WRITE_TOOLS.has(event.toolName)) return;
    const input = event.input ?? {};
    const target = input.path ?? "";
    let mirrored: string | null = null;
    if (event.toolName === "write" && typeof input.content === "string") {
      mirrored = mirror(target, input.content);
    } else if (event.toolName === "edit" && Array.isArray(input.edits)) {
      try {
        let text = readFileSync(target, "utf8");
        for (const e of input.edits) {
          if (typeof e?.oldText === "string" && typeof e?.newText === "string") {
            text = text.split(e.oldText).join(e.newText);
          }
        }
        mirrored = mirror(target, text);
      } catch {
        mirrored = null;
      }
    }
    const checkPath = mirrored ?? target;
    const reason = run(POST, POST_TIMEOUT, {
      session_id: ctx.sessionManager?.sessionId ?? "pi",
      cwd: ctx.cwd ?? ".",
      tool_name: event.toolName,
      tool_input: { ...input, path: checkPath },
    });
    if (mirrored !== null) {
      try { rmSync(mirrored, { force: true }); } catch { /* cleaned later */ }
    }
    if (reason !== null) return { block: true, reason };
    return undefined;
  });
  pi.on("turn_end", async (_event: any, ctx: any) => {
    const sm = ctx.sessionManager ?? {};
    const feedback = run(STOP, STOP_TIMEOUT, {
      session_id: sm.sessionId ?? "pi",
      cwd: ctx.cwd ?? ".",
      status: ctx.signal?.aborted ? "aborted" : "completed",
    });
    // pi cannot push Stop feedback back into the conversation (D-102): the
    // checks ran and their results are on disk; tell the person, not the model.
    if (feedback !== null && typeof ctx.ui?.notify === "function") {
      ctx.ui.notify(feedback.slice(0, 500), "warn");
    }
  });
}
`;
}

function opencodePlugin(agent: AgentProfile, cmd: HookCommand): string {
  return `${bridgeRuntime(agent.id, cmd, true)}
// opencode names file tools differently from pi; args carry absolute paths.
const WRITE_TOOLS = new Set(["write", "edit", "multiedit", "patch", "apply_patch", "bash"]);

export const Lingspark = async ({ directory }) => ({
  "tool.execute.before": async (input, output) => {
    if (!WRITE_TOOLS.has(input.tool)) return;
    const args = output.args ?? {};
    const target = args.filePath ?? args.path ?? "";
    let mirrored = null;
    if (input.tool === "write" && typeof args.content === "string") {
      mirrored = mirror(target, args.content);
    }
    const checkPath = mirrored ?? target;
    const reason = run(POST, POST_TIMEOUT, {
      session_id: input.sessionID ?? "opencode",
      cwd: directory ?? ".",
      tool_name: input.tool,
      tool_input: { ...args, filePath: checkPath },
    });
    if (mirrored !== null) {
      try { rmSync(mirrored, { force: true }); } catch { /* cleaned later */ }
    }
    // opencode turns a thrown error into the tool failure the model sees.
    if (reason !== null) throw new Error(reason);
  },
  // Named session.idle hooks do not fire in run mode; the catch-all event
  // hook does (probe: 221 events captured, D-102). opencode cannot push Stop
  // feedback back into the conversation either: checks run, results land on
  // disk and show in the setup page.
  event: async ({ event }) => {
    if (event.type !== "session.idle") return;
    run(STOP, STOP_TIMEOUT, {
      session_id: event.properties?.sessionID ?? "opencode",
      cwd: directory ?? ".",
      status: "completed",
    });
  },
});
`;
}

/** The bridge file's content for an agent, or null for non-bridge agents. */
export function bridgeContent(agent: AgentProfile, cmd: HookCommand): string | null {
  if (agent.bridge === 'pi-extension') return piExtension(agent, cmd);
  if (agent.bridge === 'opencode-plugin') return opencodePlugin(agent, cmd);
  return null;
}

/** Absolute path of an agent's bridge file. */
export function bridgePath(agent: AgentProfile, homedir: string): string {
  if (agent.configFile === null) throw new InstallError(msg.install.unknownAgent(agent.id));
  return path.join(homedir, ...agent.configFile);
}

/** The file:// URL an opencode plugin entry points at (forward slashes). */
export function opencodePluginUrl(agent: AgentProfile, homedir: string): string {
  const p = bridgePath(agent, homedir).split(path.sep).join('/');
  return `file:///${p.replace(/^\/+/, '')}`;
}

function stamp(): string {
  const d = new Date();
  const p = (n: number): string => String(n).padStart(2, '0');
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}T${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

/**
 * Writes a bridge file, replacing an older lingspark bridge. A file that is
 * not recognisably ours is never clobbered. Backs up a previous bridge, like
 * applyChange does for configs. Returns whether anything changed.
 */
export function writeBridge(file: string, content: string): boolean {
  let before: string | null = null;
  try {
    before = readFileSync(file, 'utf8');
  } catch {
    before = null;
  }
  if (before === content) return false;
  if (before !== null && ourCommandsInText(before).length === 0) {
    // Not a lingspark bridge: refuse to clobber a stranger's file.
    throw new InstallError(msg.install.notOurs(file));
  }
  mkdirSync(path.dirname(file), { recursive: true });
  const tmp = `${file}.${String(process.pid)}.tmp`;
  try {
    writeFileSync(tmp, content, 'utf8');
    renameSync(tmp, file);
  } catch (err: unknown) {
    rmSync(tmp, { force: true });
    throw new InstallError(msg.install.bridgeWriteFailed(file, String(err)));
  }
  if (before !== null) {
    let backup = `${file}.lingspark-backup-${stamp()}`;
    for (let n = 1; existsSync(backup); n++) backup = `${file}.lingspark-backup-${stamp()}-${String(n)}`;
    writeFileSync(backup, before, 'utf8');
  }
  return true;
}

/** Removes a bridge file we installed; returns whether it was there. */
export function removeBridge(file: string): boolean {
  let text: string;
  try {
    text = readFileSync(file, 'utf8');
  } catch {
    return false;
  }
  if (ourCommandsInText(text).length === 0) return false; // not ours: leave it
  rmSync(file, { force: true });
  return true;
}

/** A planned bridge write, shaped like ConfigChange so the CLI can diff it. */
export interface BridgeChange {
  readonly file: string;
  readonly existed: boolean;
  readonly before: string;
  readonly after: string;
  readonly changed: boolean;
}

/**
 * What installing or uninstalling an agent's bridge would do, without doing
 * it. Install diffs the generated file against what is on disk; uninstall
 * reports whether a bridge we installed is there. opencode's config entry is
 * not part of the plan: it is a side merge the apply step performs.
 */
export function planBridge(agent: AgentProfile, mode: 'install' | 'uninstall', cmd: HookCommand, homedir: string): BridgeChange {
  const content = bridgeContent(agent, cmd);
  if (content === null) throw new InstallError(msg.install.unknownAgent(agent.id));
  const file = bridgePath(agent, homedir);
  let before = '';
  let existed = false;
  try {
    before = readFileSync(file, 'utf8');
    existed = true;
  } catch {
    before = '';
  }
  if (mode === 'uninstall') {
    const ours = existed && ourCommandsInText(before).length > 0;
    return { file, existed, before, after: '', changed: ours };
  }
  return { file, existed, before, after: content, changed: !existed || before !== content };
}

/**
 * Applies a bridge install or uninstall: writes or removes the bridge file,
 * and merges opencode's plugin entry in its config. Returns whether the
 * bridge file changed.
 */
export function applyBridge(agent: AgentProfile, mode: 'install' | 'uninstall', cmd: HookCommand, homedir: string): boolean {
  const file = bridgePath(agent, homedir);
  const changed = mode === 'install'
    ? writeBridge(file, bridgeContent(agent, cmd) ?? '')
    : removeBridge(file);
  if (agent.bridge === 'opencode-plugin') {
    const cfg = path.join(homedir, '.config', 'opencode', 'opencode.json');
    const change = planChange(cfg, (c) =>
      mode === 'install' ? withPluginInstalled(c, opencodePluginUrl(agent, homedir)) : withPluginRemoved(c, opencodePluginUrl(agent, homedir)));
    applyChange(change);
  }
  return changed;
}
