// Generated by `LINGSPARK_CONVERGE_UPDATE=1 pnpm vitest run packages/core/src/e2e`.
// Do not hand-edit: this is the measured curve for the rules as they are now.
//
// Regenerate on purpose, and read the diff -- it is the only record of whether
// a change to a rule made the product better or worse.
import type { Metric } from './converge.js';

export const BASELINE: Readonly<Record<string, Metric>> = {
  'prd-self-contradiction': {"rounds":3,"converged":true,"finalErrors":0,"finalWarnings":0,"curve":[7,1,0],"rulesSeen":["D101","D103","D104","D108","D110","D111"]},
  'tech-design-halfwidth-and-repeat': {"rounds":2,"converged":true,"finalErrors":0,"finalWarnings":0,"curve":[7,0],"rulesSeen":["D106","D109","D110"]},
  'report-vocabulary-and-refs': {"rounds":3,"converged":true,"finalErrors":0,"finalWarnings":0,"curve":[6,5,0],"rulesSeen":["D102","D103","D106","D110"]},
  'clean-control': {"rounds":1,"converged":true,"finalErrors":0,"finalWarnings":0,"curve":[0],"rulesSeen":[]},
  'generic-todo-leaves-empty-section': {"rounds":3,"converged":true,"finalErrors":0,"finalWarnings":0,"curve":[1,1,0],"rulesSeen":["D108","D110"]},
};
