// The convergence gate.
//
// `pnpm run test` runs this, so a change that makes the checker stop catching
// something -- or start catching something it should not -- fails the build
// with a diff instead of being noticed by a user three weeks later.
//
// How to read a failure: the report above the assertion prints the error curve
// per round. Rising numbers mean a repair now makes the document worse, or a
// rule that used to fire no longer does. Flat-but-nonzero means the checker is
// still finding it and the scripted agent cannot act on it. A new rule id in
// `introduced` is the one to look at first.
//
// After an intentional change, rewrite the golden file with
//   LINGSPARK_CONVERGE_UPDATE=1 pnpm vitest run packages/core/src/e2e
// and read the diff in the PR: it is the before/after of the product, not just
// of the test.

import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { formatReport, loadBuiltinRules, metricOf, runScenario, type Scenario, type ScenarioResult } from './converge.js';
import { SCENARIOS } from './scenarios.js';
import { BASELINE } from './baseline.js';

const BASELINE_FILE = path.join(path.dirname(fileURLToPath(import.meta.url)), 'baseline.ts');
const builtinRules = loadBuiltinRules();
const update = process.env['LINGSPARK_CONVERGE_UPDATE'] === '1';

const results: ScenarioResult[] = [];
for (const scenario of SCENARIOS) {
  results.push(await runScenario(scenario, { builtinRules }));
}

// One report for the whole run, always printed: in CI it is the failure
// message's preamble, and locally it is the answer to "did my change help".
console.log(formatReport(results, BASELINE));

if (update) {
  const entries = results.map((r) => `  '${r.id}': ${JSON.stringify(metricOf(r))},`).join('\n');
  writeFileSync(
    BASELINE_FILE,
    `// Generated by \`LINGSPARK_CONVERGE_UPDATE=1 pnpm vitest run packages/core/src/e2e\`.
// Do not hand-edit: this is the measured curve for the rules as they are now.
//
// Regenerate on purpose, and read the diff -- it is the only record of whether
// a change to a rule made the product better or worse.
import type { Metric } from './converge.js';

export const BASELINE: Readonly<Record<string, Metric>> = {
${entries}
};
`,
    'utf8',
  );
  console.log(`已写入基线：${path.relative(process.cwd(), BASELINE_FILE)}`);
}

/** A round never reports strictly more than the round before it left behind. */
const strictlyBetter = (r: ScenarioResult): boolean => {
  const curve = metricOf(r).curve;
  return curve.every((n, i) => i === 0 || n <= (curve[i - 1] ?? n));
};

describe('agent output converges on the target', () => {
  for (const r of results) {
    it(`${r.id}：${r.title}`, () => {
      // Converged: some round reached zero diagnostics. `finalErrors` alone
      // would also pass when the run simply ran out of turns, so the flag is
      // asserted too and whatever is still standing is named in the failure.
      expect(
        r.converged,
        `${r.id} 没有收敛：仍未清掉 ${r.stuck.join(' ') || '（无）'}，曲线 ${metricOf(r).curve.join(' → ')}`,
      ).toBe(true);
      expect(r.finalErrors, `${r.id} 还有 error 级问题没修掉`).toBe(0);
      expect(r.finalWarnings, `${r.id} 还有 warning 级问题没修掉`).toBe(0);
    });
  }
});

describe('the harness itself', () => {
  it('a clean document is left alone, so convergence is not the repairs being generous', () => {
    const clean = results.find((r) => r.id === 'clean-control');
    expect(clean, '场景集里少了 clean-control').toBeDefined();
    expect(metricOf(clean as ScenarioResult).curve).toEqual([0]);
    expect(clean?.rounds[0]?.fixed).toBe(0);
  });

  it('every rule a scenario is written to trip actually fired', () => {
    // The oracle. Without it "converged" only means the checker went quiet,
    // which is also what a rule that stopped working looks like.
    for (const r of results) {
      expect(
        r.rulesMissed,
        `${r.id} 本该触发 ${r.rulesMissed.join(' ')}，却一次都没报出来：规则可能变暗了，或者它的正例写法已经不适用了`,
      ).toEqual([]);
    }
  });

  it('a rule that stops firing is caught, not mistaken for a clean document', async () => {
    // The change under test: D101 no longer runs. Nothing else moves.
    const prd = SCENARIOS.find((s) => s.id === 'prd-self-contradiction');
    expect(prd).toBeDefined();
    const weakened = await runScenario(prd as Scenario, { builtinRules: builtinRules.filter((r) => r.file !== 'D101.yaml') });

    // The checker is happy -- the contradictions are still in the text, it
    // just stopped noticing -- so only the declared expectation can tell.
    expect(weakened.converged).toBe(true);
    expect(weakened.rulesMissed).toEqual(['D101']);
    expect(results.find((r) => r.id === 'prd-self-contradiction')?.rulesMissed).toEqual([]);
  });

  it('the one repair that uncovers the next problem is the one we already know about', () => {
    // Deleting a placeholder is correct and leaves its section empty, so D110
    // has to fire on the next round. Pinning that exact set means a *new*
    // interference between two fixes shows up as a failure instead of a
    // longer curve nobody reads.
    const introduced = results.flatMap((r) => r.rounds.flatMap((round) => round.introduced));
    expect(introduced).toEqual(['D110']);
  });

  it('nothing the checker reported went unhandled', () => {
    const unfixed = results.flatMap((r) => r.rounds.filter((round) => round.unfixed > 0).map((round) => `${r.id}#${round.round}`));
    expect(unfixed, `这些诊断报了但脚本 agent 改不了：${unfixed.join(' ')}`).toEqual([]);
  });
});

// Skipped on the run that rewrites the golden file: the module has already
// read the old one, so comparing against it would only report the write that
// just happened as a difference.
describe.skipIf(update)('golden curve', () => {
  for (const r of results) {
    it(`${r.id} 的收敛曲线与基线一致`, () => {
      const now = metricOf(r);
      const before = BASELINE[r.id];
      expect(before, `基线里没有 ${r.id}，用 LINGSPARK_CONVERGE_UPDATE=1 重新生成`).toBeDefined();
      const same = JSON.stringify(now) === JSON.stringify(before);
      if (same) {
        expect(now).toEqual(before);
        return;
      }
      expect(
        true,
        `曲线变了。基线 ${before?.curve.join(' → ')}（${before?.converged ? `第 ${String(before?.rounds)} 轮收敛` : '未收敛'}），` +
          `现在 ${now.curve.join(' → ')}（${now.converged ? `第 ${String(now.rounds)} 轮收敛` : '未收敛'}）。` +
          '这是改动的效果；确认是有意为之再跑 LINGSPARK_CONVERGE_UPDATE=1 更新基线。',
      ).toBe(true);
    });
  }

  it('the measured curve never got worse than the baseline', () => {
    for (const r of results) {
      const before = BASELINE[r.id];
      if (before === undefined) continue;
      expect(strictlyBetter(r), `${r.id} 的曲线比基线更差`).toBe(true);
    }
  });
});

describe.skipIf(update)('the golden file is in step with the scenarios', () => {
  it('every scenario has a baseline entry and no entry is left over', () => {
    const ids = SCENARIOS.map((s) => s.id).sort();
    expect(Object.keys(BASELINE).sort()).toEqual(ids);
  });

  it('the baseline is loadable TypeScript, not a stale copy', () => {
    const source = readFileSync(BASELINE_FILE, 'utf8');
    expect(source).toContain('export const BASELINE');
    for (const id of SCENARIOS.map((s) => s.id)) {
      expect(source).toContain(`'${id}'`);
    }
  });
});
